targets:
  $default:
    builders:
      isar_community_generator:
        options:
          enable_experiment: ["dot-shorthands"]
      source_gen:combining_builder:
        options:
          enable_experiment: ["dot-shorthands"]
