// Mocks generated by Mockito 5.4.6 from annotations
// in daily_os/test/features/knowledge_base/logic/block_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:daily_os/features/knowledge_base/domain/entities/block_entity.dart'
    as _i7;
import 'package:daily_os/features/knowledge_base/domain/entities/folder_entity.dart'
    as _i5;
import 'package:daily_os/features/knowledge_base/domain/entities/page_entity.dart'
    as _i6;
import 'package:daily_os/features/knowledge_base/domain/entities/property_entity.dart'
    as _i8;
import 'package:daily_os/features/knowledge_base/domain/entities/workspace_entity.dart'
    as _i4;
import 'package:daily_os/features/knowledge_base/domain/repositories/i_knowledge_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IKnowledgeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIKnowledgeRepository extends _i1.Mock
    implements _i2.IKnowledgeRepository {
  MockIKnowledgeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.WorkspaceEntity>> getWorkspaces() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspaces, []),
            returnValue: _i3.Future<List<_i4.WorkspaceEntity>>.value(
              <_i4.WorkspaceEntity>[],
            ),
          )
          as _i3.Future<List<_i4.WorkspaceEntity>>);

  @override
  _i3.Future<_i4.WorkspaceEntity?> getWorkspace(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkspace, [id]),
            returnValue: _i3.Future<_i4.WorkspaceEntity?>.value(),
          )
          as _i3.Future<_i4.WorkspaceEntity?>);

  @override
  _i3.Future<void> createWorkspace(_i4.WorkspaceEntity? workspace) =>
      (super.noSuchMethod(
            Invocation.method(#createWorkspace, [workspace]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateWorkspace(_i4.WorkspaceEntity? workspace) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkspace, [workspace]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWorkspace(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkspace, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.FolderEntity>> getRootFolders(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getRootFolders, [workspaceId]),
            returnValue: _i3.Future<List<_i5.FolderEntity>>.value(
              <_i5.FolderEntity>[],
            ),
          )
          as _i3.Future<List<_i5.FolderEntity>>);

  @override
  _i3.Future<List<_i5.FolderEntity>> getChildFolders(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getChildFolders, [parentId]),
            returnValue: _i3.Future<List<_i5.FolderEntity>>.value(
              <_i5.FolderEntity>[],
            ),
          )
          as _i3.Future<List<_i5.FolderEntity>>);

  @override
  _i3.Future<_i5.FolderEntity?> getFolder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFolder, [id]),
            returnValue: _i3.Future<_i5.FolderEntity?>.value(),
          )
          as _i3.Future<_i5.FolderEntity?>);

  @override
  _i3.Future<void> createFolder(_i5.FolderEntity? folder) =>
      (super.noSuchMethod(
            Invocation.method(#createFolder, [folder]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateFolder(_i5.FolderEntity? folder) =>
      (super.noSuchMethod(
            Invocation.method(#updateFolder, [folder]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> moveFolder(String? folderId, String? newParentId) =>
      (super.noSuchMethod(
            Invocation.method(#moveFolder, [folderId, newParentId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteFolder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFolder, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> permanentlyDeleteFolder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDeleteFolder, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.PageEntity>> getPages(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#getPages, [folderId]),
            returnValue: _i3.Future<List<_i6.PageEntity>>.value(
              <_i6.PageEntity>[],
            ),
          )
          as _i3.Future<List<_i6.PageEntity>>);

  @override
  _i3.Future<_i6.PageEntity?> getPage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPage, [id]),
            returnValue: _i3.Future<_i6.PageEntity?>.value(),
          )
          as _i3.Future<_i6.PageEntity?>);

  @override
  _i3.Future<void> createPage(_i6.PageEntity? page) =>
      (super.noSuchMethod(
            Invocation.method(#createPage, [page]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePage(_i6.PageEntity? page) =>
      (super.noSuchMethod(
            Invocation.method(#updatePage, [page]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> movePage(String? pageId, String? newFolderId) =>
      (super.noSuchMethod(
            Invocation.method(#movePage, [pageId, newFolderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePage, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> permanentlyDeletePage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDeletePage, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.PageEntity>> searchPages(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPages, [query]),
            returnValue: _i3.Future<List<_i6.PageEntity>>.value(
              <_i6.PageEntity>[],
            ),
          )
          as _i3.Future<List<_i6.PageEntity>>);

  @override
  _i3.Future<List<_i7.BlockEntity>> getBlocks(String? pageId) =>
      (super.noSuchMethod(
            Invocation.method(#getBlocks, [pageId]),
            returnValue: _i3.Future<List<_i7.BlockEntity>>.value(
              <_i7.BlockEntity>[],
            ),
          )
          as _i3.Future<List<_i7.BlockEntity>>);

  @override
  _i3.Future<void> addBlock(_i7.BlockEntity? block) =>
      (super.noSuchMethod(
            Invocation.method(#addBlock, [block]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBlock(_i7.BlockEntity? block) =>
      (super.noSuchMethod(
            Invocation.method(#updateBlock, [block]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBlock(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBlock, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reorderBlocks(String? pageId, List<String>? blockIds) =>
      (super.noSuchMethod(
            Invocation.method(#reorderBlocks, [pageId, blockIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.PropertyEntity>> getProperties(String? pageId) =>
      (super.noSuchMethod(
            Invocation.method(#getProperties, [pageId]),
            returnValue: _i3.Future<List<_i8.PropertyEntity>>.value(
              <_i8.PropertyEntity>[],
            ),
          )
          as _i3.Future<List<_i8.PropertyEntity>>);

  @override
  _i3.Future<void> addProperty(_i8.PropertyEntity? property) =>
      (super.noSuchMethod(
            Invocation.method(#addProperty, [property]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProperty(_i8.PropertyEntity? property) =>
      (super.noSuchMethod(
            Invocation.method(#updateProperty, [property]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProperty(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProperty, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.FolderEntity>> getDeletedFolders() =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedFolders, []),
            returnValue: _i3.Future<List<_i5.FolderEntity>>.value(
              <_i5.FolderEntity>[],
            ),
          )
          as _i3.Future<List<_i5.FolderEntity>>);

  @override
  _i3.Future<List<_i6.PageEntity>> getDeletedPages() =>
      (super.noSuchMethod(
            Invocation.method(#getDeletedPages, []),
            returnValue: _i3.Future<List<_i6.PageEntity>>.value(
              <_i6.PageEntity>[],
            ),
          )
          as _i3.Future<List<_i6.PageEntity>>);

  @override
  _i3.Future<void> restoreFolder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFolder, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restorePage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#restorePage, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> emptyTrash() =>
      (super.noSuchMethod(
            Invocation.method(#emptyTrash, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
