// Mocks generated by Mockito 5.4.6 from annotations
// in daily_os/test/features/knowledge_base/data/repositories/knowledge_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:daily_os/features/knowledge_base/data/datasources/local/block_local_datasource.dart'
    as _i10;
import 'package:daily_os/features/knowledge_base/data/datasources/local/folder_local_datasource.dart'
    as _i6;
import 'package:daily_os/features/knowledge_base/data/datasources/local/page_local_datasource.dart'
    as _i8;
import 'package:daily_os/features/knowledge_base/data/datasources/local/property_local_datasource.dart'
    as _i12;
import 'package:daily_os/features/knowledge_base/data/datasources/local/workspace_local_datasource.dart'
    as _i4;
import 'package:daily_os/features/knowledge_base/data/dtos/block_dto.dart'
    as _i11;
import 'package:daily_os/features/knowledge_base/data/dtos/folder_dto.dart'
    as _i7;
import 'package:daily_os/features/knowledge_base/data/dtos/page_dto.dart'
    as _i9;
import 'package:daily_os/features/knowledge_base/data/dtos/property_dto.dart'
    as _i13;
import 'package:daily_os/features/knowledge_base/data/dtos/workspace_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:uuid/data.dart' as _i15;
import 'package:uuid/uuid.dart' as _i14;
import 'package:uuid/uuid_value.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkspaceDTO_0 extends _i1.SmartFake implements _i2.WorkspaceDTO {
  _FakeWorkspaceDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUuidValue_1 extends _i1.SmartFake implements _i3.UuidValue {
  _FakeUuidValue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkspaceLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceLocalDatasource extends _i1.Mock
    implements _i4.WorkspaceLocalDatasource {
  MockWorkspaceLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.WorkspaceDTO>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i5.Future<List<_i2.WorkspaceDTO>>.value(
              <_i2.WorkspaceDTO>[],
            ),
          )
          as _i5.Future<List<_i2.WorkspaceDTO>>);

  @override
  _i5.Future<_i2.WorkspaceDTO?> getByUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getByUid, [uid]),
            returnValue: _i5.Future<_i2.WorkspaceDTO?>.value(),
          )
          as _i5.Future<_i2.WorkspaceDTO?>);

  @override
  _i5.Future<void> save(_i2.WorkspaceDTO? workspace) =>
      (super.noSuchMethod(
            Invocation.method(#save, [workspace]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.WorkspaceDTO> getOrCreateDefault() =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateDefault, []),
            returnValue: _i5.Future<_i2.WorkspaceDTO>.value(
              _FakeWorkspaceDTO_0(
                this,
                Invocation.method(#getOrCreateDefault, []),
              ),
            ),
          )
          as _i5.Future<_i2.WorkspaceDTO>);
}

/// A class which mocks [FolderLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFolderLocalDatasource extends _i1.Mock
    implements _i6.FolderLocalDatasource {
  MockFolderLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i7.FolderDTO>> getRootFolders(String? workspaceUid) =>
      (super.noSuchMethod(
            Invocation.method(#getRootFolders, [workspaceUid]),
            returnValue: _i5.Future<List<_i7.FolderDTO>>.value(
              <_i7.FolderDTO>[],
            ),
          )
          as _i5.Future<List<_i7.FolderDTO>>);

  @override
  _i5.Future<List<_i7.FolderDTO>> getChildren(String? parentUid) =>
      (super.noSuchMethod(
            Invocation.method(#getChildren, [parentUid]),
            returnValue: _i5.Future<List<_i7.FolderDTO>>.value(
              <_i7.FolderDTO>[],
            ),
          )
          as _i5.Future<List<_i7.FolderDTO>>);

  @override
  _i5.Future<_i7.FolderDTO?> getByUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getByUid, [uid]),
            returnValue: _i5.Future<_i7.FolderDTO?>.value(),
          )
          as _i5.Future<_i7.FolderDTO?>);

  @override
  _i5.Future<List<_i7.FolderDTO>> getAllForWorkspace(String? workspaceUid) =>
      (super.noSuchMethod(
            Invocation.method(#getAllForWorkspace, [workspaceUid]),
            returnValue: _i5.Future<List<_i7.FolderDTO>>.value(
              <_i7.FolderDTO>[],
            ),
          )
          as _i5.Future<List<_i7.FolderDTO>>);

  @override
  _i5.Future<void> save(_i7.FolderDTO? folder) =>
      (super.noSuchMethod(
            Invocation.method(#save, [folder]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> softDelete(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> restore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#restore, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.FolderDTO>> getDeleted() =>
      (super.noSuchMethod(
            Invocation.method(#getDeleted, []),
            returnValue: _i5.Future<List<_i7.FolderDTO>>.value(
              <_i7.FolderDTO>[],
            ),
          )
          as _i5.Future<List<_i7.FolderDTO>>);

  @override
  _i5.Future<void> permanentlyDelete(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDelete, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> move(String? uid, String? newParentUid) =>
      (super.noSuchMethod(
            Invocation.method(#move, [uid, newParentUid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PageLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPageLocalDatasource extends _i1.Mock
    implements _i8.PageLocalDatasource {
  MockPageLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i9.PageDTO>> getByFolder(String? folderUid) =>
      (super.noSuchMethod(
            Invocation.method(#getByFolder, [folderUid]),
            returnValue: _i5.Future<List<_i9.PageDTO>>.value(<_i9.PageDTO>[]),
          )
          as _i5.Future<List<_i9.PageDTO>>);

  @override
  _i5.Future<_i9.PageDTO?> getByUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getByUid, [uid]),
            returnValue: _i5.Future<_i9.PageDTO?>.value(),
          )
          as _i5.Future<_i9.PageDTO?>);

  @override
  _i5.Future<void> save(_i9.PageDTO? page) =>
      (super.noSuchMethod(
            Invocation.method(#save, [page]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> move(String? uid, String? newFolderUid) =>
      (super.noSuchMethod(
            Invocation.method(#move, [uid, newFolderUid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> softDelete(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#softDelete, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> restore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#restore, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.PageDTO>> getDeleted() =>
      (super.noSuchMethod(
            Invocation.method(#getDeleted, []),
            returnValue: _i5.Future<List<_i9.PageDTO>>.value(<_i9.PageDTO>[]),
          )
          as _i5.Future<List<_i9.PageDTO>>);

  @override
  _i5.Future<void> permanentlyDelete(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDelete, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.PageDTO>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i5.Future<List<_i9.PageDTO>>.value(<_i9.PageDTO>[]),
          )
          as _i5.Future<List<_i9.PageDTO>>);
}

/// A class which mocks [BlockLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockLocalDatasource extends _i1.Mock
    implements _i10.BlockLocalDatasource {
  MockBlockLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i11.BlockDTO>> getByPage(String? pageUid) =>
      (super.noSuchMethod(
            Invocation.method(#getByPage, [pageUid]),
            returnValue: _i5.Future<List<_i11.BlockDTO>>.value(
              <_i11.BlockDTO>[],
            ),
          )
          as _i5.Future<List<_i11.BlockDTO>>);

  @override
  _i5.Future<_i11.BlockDTO?> getByUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getByUid, [uid]),
            returnValue: _i5.Future<_i11.BlockDTO?>.value(),
          )
          as _i5.Future<_i11.BlockDTO?>);

  @override
  _i5.Future<void> save(_i11.BlockDTO? block) =>
      (super.noSuchMethod(
            Invocation.method(#save, [block]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveAll(List<_i11.BlockDTO>? blocks) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [blocks]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAllForPage(String? pageUid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllForPage, [pageUid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> reorder(String? pageUid, List<String>? blockUids) =>
      (super.noSuchMethod(
            Invocation.method(#reorder, [pageUid, blockUids]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PropertyLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPropertyLocalDatasource extends _i1.Mock
    implements _i12.PropertyLocalDatasource {
  MockPropertyLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i13.PropertyDTO>> getByPage(String? pageUid) =>
      (super.noSuchMethod(
            Invocation.method(#getByPage, [pageUid]),
            returnValue: _i5.Future<List<_i13.PropertyDTO>>.value(
              <_i13.PropertyDTO>[],
            ),
          )
          as _i5.Future<List<_i13.PropertyDTO>>);

  @override
  _i5.Future<_i13.PropertyDTO?> getByUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getByUid, [uid]),
            returnValue: _i5.Future<_i13.PropertyDTO?>.value(),
          )
          as _i5.Future<_i13.PropertyDTO?>);

  @override
  _i5.Future<void> save(_i13.PropertyDTO? property) =>
      (super.noSuchMethod(
            Invocation.method(#save, [property]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAllForPage(String? pageUid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllForPage, [pageUid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [Uuid].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuid extends _i1.Mock implements _i14.Uuid {
  MockUuid() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String v1({Map<String, dynamic>? options, _i15.V1Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v1, [], {#options: options, #config: config}),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#v1, [], {#options: options, #config: config}),
            ),
          )
          as String);

  @override
  List<int> v1buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i15.V1Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v1buffer,
              [buffer],
              {#options: options, #config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v1obj({
    Map<String, dynamic>? options,
    _i15.V1Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1obj, [], {#options: options, #config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v1obj, [], {
                #options: options,
                #config: config,
              }),
            ),
          )
          as _i3.UuidValue);

  @override
  String v4({Map<String, dynamic>? options, _i15.V4Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v4, [], {#options: options, #config: config}),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#v4, [], {#options: options, #config: config}),
            ),
          )
          as String);

  @override
  List<int> v4buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i15.V4Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v4buffer,
              [buffer],
              {#options: options, #config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v4obj({
    Map<String, dynamic>? options,
    _i15.V4Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v4obj, [], {#options: options, #config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v4obj, [], {
                #options: options,
                #config: config,
              }),
            ),
          )
          as _i3.UuidValue);

  @override
  String v5(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i15.V5Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v5,
              [namespace, name],
              {#options: options, #config: config},
            ),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(
                #v5,
                [namespace, name],
                {#options: options, #config: config},
              ),
            ),
          )
          as String);

  @override
  List<int> v5buffer(
    String? namespace,
    String? name,
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i15.V5Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v5buffer,
              [namespace, name, buffer],
              {#options: options, #config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v5obj(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i15.V5Options? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v5obj,
              [namespace, name],
              {#options: options, #config: config},
            ),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(
                #v5obj,
                [namespace, name],
                {#options: options, #config: config},
              ),
            ),
          )
          as _i3.UuidValue);

  @override
  String v6({_i15.V6Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v6, [], {#config: config}),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#v6, [], {#config: config}),
            ),
          )
          as String);

  @override
  List<int> v6buffer(
    List<int>? buffer, {
    _i15.V6Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v6buffer,
              [buffer],
              {#config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v6obj({_i15.V6Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v6obj, [], {#config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v6obj, [], {#config: config}),
            ),
          )
          as _i3.UuidValue);

  @override
  String v7({_i15.V7Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v7, [], {#config: config}),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#v7, [], {#config: config}),
            ),
          )
          as String);

  @override
  List<int> v7buffer(
    List<int>? buffer, {
    _i15.V7Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v7buffer,
              [buffer],
              {#config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v7obj({_i15.V7Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v7obj, [], {#config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v7obj, [], {#config: config}),
            ),
          )
          as _i3.UuidValue);

  @override
  String v8({_i15.V8Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v8, [], {#config: config}),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#v8, [], {#config: config}),
            ),
          )
          as String);

  @override
  List<int> v8buffer(
    List<int>? buffer, {
    _i15.V8Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v8buffer,
              [buffer],
              {#config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v8obj({_i15.V8Options? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v8obj, [], {#config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v8obj, [], {#config: config}),
            ),
          )
          as _i3.UuidValue);

  @override
  String v8g({_i15.V8GenericOptions? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v8g, [], {#config: config}),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#v8g, [], {#config: config}),
            ),
          )
          as String);

  @override
  List<int> v8gbuffer(
    List<int>? buffer, {
    _i15.V8GenericOptions? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #v8gbuffer,
              [buffer],
              {#config: config, #offset: offset},
            ),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i3.UuidValue v8gobj({_i15.V8GenericOptions? config}) =>
      (super.noSuchMethod(
            Invocation.method(#v8gobj, [], {#config: config}),
            returnValue: _FakeUuidValue_1(
              this,
              Invocation.method(#v8gobj, [], {#config: config}),
            ),
          )
          as _i3.UuidValue);
}
